FROM docker.io/openjdk:8-jre-slim

EXPOSE 8110

ADD target/user-service-0.0.1-SNAPSHOT.jar /user-service-0.0.1-SNAPSHOT.jar

CMD ["/usr/local/openjdk-8/bin/java", "-jar", "/user-service-0.0.1-SNAPSHOT.jar"]