apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user
  replicas: 3
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-deployment
          image: gcr.io/nagp2019-268411/user-image:v2
          ports:
            - containerPort: 8100